Barplot of number of detected feature per sample
bigomics/omicsplayground pull request #1108
Opened 2024-09-23 21:57 UTC by zitoa

Please review the barplot of number of detected features per sample. We should be able to show it tomorrow. Thanks.

2024-09-24 12:27 UTC, ESCRI11 requested changes
Couple of points for improvement

2024-09-24 12:27 UTC, ESCRI11 commented on components/board.dataview/R/dataview_plot_totalcounts.R
> +      if(res$sampleqc_plottype == "Average total abundance") {
This could be cleaner, no need to duplicate code to just change the y variable

2024-09-24 12:27 UTC, ESCRI11 commented on components/board.dataview/R/dataview_plot_totalcounts.R
> +      ## ylab <- paste0("total ", type, logtype)
Do some clean up please, no need to leave commented lines that are not useful anymore

2024-09-24 12:27 UTC, ESCRI11 commented on components/board.dataview/R/dataview_ui.R
>              info.text = "Average total counts by sample. Samples can be grouped using the {Group by} setting.",
Please update the info explaining the new feature you implemented

2024-09-26 07:10 UTC, merged

2024-10-01 08:26 UTC, zitoa commented on components/board.dataview/R/dataview_plot_totalcounts.R
> +      if(res$sampleqc_plottype == "Average total abundance") {
Thank you Xavi

2024-10-01 08:26 UTC, zitoa commented on components/board.dataview/R/dataview_plot_totalcounts.R
> +      ## ylab <- paste0("total ", type, logtype)
Thank you Xavi - it was just for my reference i will delete it

2024-10-01 08:30 UTC, zitoa commented on components/board.dataview/R/dataview_ui.R
>              info.text = "Average total counts by sample. Samples can be grouped using the {Group by} setting.",
will do thanks